declare module '@oh-my-rpg/data'
declare module '@oh-my-rpg/data/src/adventure_archetype'
declare module '@oh-my-rpg/data/src/adventure_archetype/i18n'
declare module '@oh-my-rpg/data/src/armor_component'
declare module '@oh-my-rpg/data/src/weapon_component'
